name: Testing
on: pull_request
jobs:
    testing_job:
        runs-on: ubuntu-latest
        steps:
            - name: CMake Action
              uses: threeal/cmake-action@v1.3.0
              with:
                run-build: false
        
            - name: Build the project
              run: mkdir build && cd build && cmake .. && cmake --build .
            
            - name: Run tests
              run: ./er-converter_test
        