name: Testing
on: pull_request
jobs:
    testing_job:
        runs-on: ubuntu-latest
        steps:
            - name: CMake Action
              uses: lukka/get-cmake@latest
        
            - name: Build the project
              run: cmake -B build && cmake --build build
            
            - name: Run tests
              run: ./er-converter_test
        