name: Testing
on: pull_request
jobs:
    testing_job:
        runs-on: ubuntu-latest
        steps:
            - name: CMake Action
              uses: lukka/get-cmake@latest
        
            - name: Build the project
              working-directory: ..
              run: |
                cmake -S . -B build 
                cmake --build build
            
            - name: Run tests
              working-directory: ./build
              run: ./er-converter_test
        